dependencies:
- name: nginx-ingress
  version: 1.33.5
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: external-dns
  version: 2.20.5
  repository: https://charts.bitnami.com/bitnami/
- name: kube2iam
  version: 2.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: spinnaker
  version: 2.0.0-rc1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: prometheus-operator
  version: 8.12.13
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: keycloak
  version: 8.0.0
  repository: https://codecentric.github.io/helm-charts