dependencies:
- name: ingress-nginx
  version: 3.7.1
  repository: https://kubernetes.github.io/ingress-nginx
- name: external-dns
  version: 2.20.5
  repository: https://charts.bitnami.com/bitnami/
- name: kube2iam
  version: 2.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: spinnaker
  version: 2.0.0-rc1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kube-prometheus-stack
  version: 10.0.1
  repository: https://prometheus-community.github.io/helm-charts
- name: keycloak
  version: 8.0.0
  repository: https://codecentric.github.io/helm-charts
- name: jenkins
  version: 2.5.2
  repository: https://kubernetes-charts.storage.googleapis.com/