dependencies:
- name: nginx-ingress
  version: 0.28.2
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: external-dns
  version: 0.7.5
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kube2iam
  version: 0.9.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: cert-manager
  version: 0.5.2
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: spinnaker
  version: 1.8.0
  repository: https://kubernetes-charts.storage.googleapis.com/