apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.moodleDeploy.name }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ template "kubernetes-moodle.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.moodleDeploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.moodleDeploy.name }}
    spec:
      containers:
      - name: {{ .Values.moodleDeploy.name }}
        image: {{ .Values.moodleDeploy.repository }}:{{ .Values.moodleDeploy.tag }}
        imagePullPolicy: {{ .Values.moodleDeploy.pullPolicy }}
        ports:
        - containerPort: {{ .Values.moodleDeploy.port }}