apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nginx.name }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ template "kubernetes-moodle.chart" . }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.nginx.port }}
    targetPort: {{ .Values.service.nginx.port }}
    protocol: TCP
  selector:
    app: {{ .Values.ngnixDeploy.name }}